AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template creates simple Lambda functions,
  which prints CloudFormation resource Arn from the stack.  

Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaFunctionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - dynamodb:scan
              - dynamodb:list
              - s3:ListAllMyBucket
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetBucketLocation
            Resource: 
            - arn:aws:dynamodb:eu-west-2:251045990954:table/MetadataJson
            - arn:aws:lambda:eu-west-2:251045990954:function:Stack-10-LambdaFunction-HUcUFXbCq4ZJ
            - arn:aws:s3:::dbmetadata/
            - '*'
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      Timeout: 5
      Handler: index.lambda_handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Code:
        ZipFile:
          !Sub
            - |-
              import boto3
              from datetime import date,datetime
              import csv

              def lambda_handler(event,context):
                  dynamoDB=boto3.resource("dynamodb",region_name='eu-west-2')
                  table=dynamoDB.Table('MetadataJson')
                  csv_name = 'MetaData'+str(date.today())+'-'+datetime.now().strftime("%H-%M")+'.csv'
                  i=0    
                  tabledict=table.scan(
                      ProjectionExpression="#AN,account,#S",
                      ExpressionAttributeNames={
                          '#AN':'account-name',
                          '#S':'status',
                      },
                  )
                  tableList=list(tabledict.items())
                  tableResponse=tableList[0][1]
                  tableData=[]
                  for index in range(len(tableResponse)):
                      tableData.append([tableResponse[index].get('account-name'),
                      tableResponse[index].get('account'),
                      tableResponse[index].get('status')])
                  csv_name = 'Metadata-'+str(date.today())+'-'+datetime.now().strftime("%H-%M")+'.csv'
                  with open('/tmp/'+csv_name, 'w', newline='') as csvfile:
                      filewriter = csv.writer(csvfile, delimiter= ',', quoting= csv.QUOTE_NONE)
                      filewriter.writerow(('account name', 'account ID', 'status'))
                      filewriter.writerows(tableData)
                  S3_Client = boto3.client("s3", region_name='eu-west-2')
                  allBuckets = S3_Client.list_buckets().get('Buckets')
                  foundBucket = False

                  j = 0
                  while foundBucket == False and j < len(allBuckets) :
                      if allBuckets[j].get('Name') == 'MetadataJson':
                          foundBucket = True
                      j+=1
                  if foundBucket == False:
                      S3_Client.create_bucket(
                          Bucket='MetadataJson',
                          CreateBucketConfiguration= {
                              'LocationConstraint': 'eu-west-2'
                          }        
                          
                      )
                  S3_Client.upload_file('/tmp/'+csv_name,'MetadataJson',csv_name)
            -
              lambda_function_role_arn: !Ref LambdaFunctionRole